# Optimize All Dataset Configs

Run CLASP latent Bayesian optimization for every configured dataset and save the best preprocessing, estimator, and graph settings to `data/optimized_params/`. Notebook 02 reads these files with `load_or_default_params(...)`, so this notebook provides the shared optimization baseline for visualization and evaluation.

Run `00_download_datasets.ipynb` first so the configured `.h5ad` inputs exist locally. The loop can be resumed: datasets with existing optimized parameter files are skipped unless `overwrite_existing = True`.

In [1]:
from __future__ import annotations

import os

from clasp.notebook_utils import (
    PAPER_DATASET_DOWNLOADS,
    resolve_project_root,
    run_dataset_optimization_sweep,
)

In [2]:
project_root = resolve_project_root()
os.chdir(project_root)

random_state = 0
selected_datasets = list(PAPER_DATASET_DOWNLOADS)

skip_missing_inputs = True
skip_existing_optimized = True
overwrite_existing = False
run_gplvm_refinement = True

embedding_method = "umap"
embedding_epochs = 60
invalid_score = -1e9
summary_path = project_root / "data" / "optimized_params" / "all_datasets_optimization_summary.csv"

base_n_top_genes = 1500
fixed_preprocess_params = {"max_cells": 1000}
base_estimator_params = {"n_components": 60}
base_graph_params = {
    "n_neighbors": 15,
    "intra_fraction": 0.5,
    "n_inter_edges": 2,
    "metric": "euclidean",
    "assignment_quantile": 0.8,
    "hubness_correction": "csls",
    "hubness_k": 10,
    "rank_correction": True,
    "edge_weighting": "binary",
    "mutual_neighbors": False,
    "neighbor_mode": "distance",
    "symmetrize": True,
}

preprocess_search_space = {
    "n_top_genes": {"type": "int", "bounds": [500, 2000]},
}
estimator_search_space = {
    "n_components": {"type": "int", "bounds": [20, 100]},
}
graph_search_space = {
    "n_neighbors": {"type": "int", "bounds": [5, 35]},
    "intra_fraction": {"type": "float", "bounds": [0.2, 0.9]},
    "n_inter_edges": {"type": "int", "bounds": [1, 6]},
    "assignment_quantile": {"type": "float", "bounds": [0.1, 1.0]},
    "hubness_k": {"type": "int", "bounds": [3, 20]},
    "rank_correction": {"type": "categorical", "values": [False, True]},
    "edge_weighting": {"type": "categorical", "values": ["binary", "distance"]},
    "inter_edge_mode": {"type": "categorical", "values": ["propagate_neighbors", "assignment"]},
    "mutual_neighbors": {"type": "categorical", "values": [False, True]},
}

compact_radii = {
    "n_top_genes": 300,
    "n_components": 20,
    "n_neighbors": 6,
    "intra_fraction": 0.1,
    "n_inter_edges": 2,
    "assignment_quantile": 0.15,
    "hubness_k": 4,
}

pca_bo_settings = {
    "n_initial": 6,
    "latent_dim": 3,
    "n_iterations": 12,
    "embedding_model": "pca",
    "acquisition": "ei",
    "batch_size": 1,
}

gplvm_bo_settings = {
    "n_initial": 6,
    "latent_dim": 3,
    "n_iterations": 12,
    "embedding_model": "gplvm",
    "acquisition": "ei",
    "batch_size": 1,
}

selected_datasets

['scib_pancreas',
 'scib_lung_atlas',
 'scib_immune_human',
 'scib_immune_human_mouse',
 'cellrank_bone_marrow',
 'cellrank_lung',
 'cellrank_pancreas',
 'cellrank_reprogramming_schiebinger',
 'cellrank_reprogramming_morris',
 'zebrafish']

In [ ]:
summary = run_dataset_optimization_sweep(
    selected_datasets,
    project_root=project_root,
    random_state=random_state,
    skip_missing_inputs=skip_missing_inputs,
    skip_existing_optimized=skip_existing_optimized,
    overwrite_existing=overwrite_existing,
    run_gplvm_refinement=run_gplvm_refinement,
    embedding_method=embedding_method,
    embedding_epochs=embedding_epochs,
    invalid_score=invalid_score,
    summary_path=summary_path,
    fixed_preprocess_params=fixed_preprocess_params,
    base_n_top_genes=base_n_top_genes,
    base_estimator_params=base_estimator_params,
    base_graph_params=base_graph_params,
    preprocess_search_space=preprocess_search_space,
    estimator_search_space=estimator_search_space,
    graph_search_space=graph_search_space,
    compact_radii=compact_radii,
    pca_bo_settings=pca_bo_settings,
    gplvm_bo_settings=gplvm_bo_settings,
    display_fn=display,
)

summary

[1/10] scib_pancreas
status=skipped_existing
best_model=gplvm
best_score=1.07715
pca_best_score=1.05435
gplvm_best_score=1.07715
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 830,
  "normalize": false
}
estimator params:
{
  "n_components": 66
}
graph params:
{
  "assignment_quantile": 0.6350850882027708,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 17,
  "inter_edge_mode": "assignment",
  "intra_fraction": 0.5368815869969734,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 4,
  "n_neighbors": 21,
  "neighbor_mode": "distance",
  "rank_correction": false,
  "symmetrize": true
}

                                                                             0
dataset                                                          scib_pancreas
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                        skipped_existing
best_model                                                               gplvm
best_score                                                             1.07715
pca_best_score                                                         1.05435
gplvm_best_score                                                       1.07715
optimized_preprocess_params  {'create_artificial_batch': False, 'hvg_flavor...
optimized_estimator_params                                {'n_components': 66}
optimized_graph_params       {'assignment_quantile': 0.6350850882027708, 'e...

[2/10] scib_lung_atlas
status=skipped_existing
best_model=pca
best_score=0.8518
pca_best_score=0.8518
gplvm_best_score=0.8469
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1483,
  "normalize": false
}
estimator params:
{
  "n_components": 83
}
graph params:
{
  "assignment_quantile": 0.15197683790092514,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 9,
  "inter_edge_mode": "assignment",
  "intra_fraction": 0.3844811722886121,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 2,
  "n_neighbors": 19,
  "neighbor_mode": "distance",
  "rank_correction": true,
  "symmetrize": true
}

                                                                             1
dataset                                                        scib_lung_atlas
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                        skipped_existing
best_model                                                                 pca
best_score                                                              0.8518
pca_best_score                                                          0.8518
gplvm_best_score                                                        0.8469
optimized_preprocess_params  {'create_artificial_batch': False, 'hvg_flavor...
optimized_estimator_params                                {'n_components': 83}
optimized_graph_params       {'assignment_quantile': 0.15197683790092514, '...

[3/10] scib_immune_human
status=skipped_existing
best_model=gplvm
best_score=0.91705
pca_best_score=0.90955
gplvm_best_score=0.91705
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1000,
  "normalize": false
}
estimator params:
{
  "n_components": 75
}
graph params:
{
  "assignment_quantile": 0.8756814709874358,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 18,
  "inter_edge_mode": "assignment",
  "intra_fraction": 0.5139120411793653,
  "metric": "euclidean",
  "mutual_neighbors": false,
  "n_inter_edges": 3,
  "n_neighbors": 9,
  "neighbor_mode": "distance",
  "rank_correction": false,
  "symmetrize": true
}

                                                                             2
dataset                                                      scib_immune_human
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                        skipped_existing
best_model                                                               gplvm
best_score                                                             0.91705
pca_best_score                                                         0.90955
gplvm_best_score                                                       0.91705
optimized_preprocess_params  {'create_artificial_batch': False, 'hvg_flavor...
optimized_estimator_params                                {'n_components': 75}
optimized_graph_params       {'assignment_quantile': 0.8756814709874358, 'e...

[4/10] scib_immune_human_mouse
status=skipped_existing
best_model=gplvm
best_score=0.7569
pca_best_score=0.7191000000000001
gplvm_best_score=0.7569
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1457,
  "normalize": false
}
estimator params:
{
  "n_components": 78
}
graph params:
{
  "assignment_quantile": 0.32725183496615845,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 7,
  "inter_edge_mode": "assignment",
  "intra_fraction": 0.2683325656076117,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 4,
  "n_neighbors": 23,
  "neighbor_mode": "distance",
  "rank_correction": true,
  "symmetrize": true
}

                                                                             3
dataset                                                scib_immune_human_mouse
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                        skipped_existing
best_model                                                               gplvm
best_score                                                              0.7569
pca_best_score                                                          0.7191
gplvm_best_score                                                        0.7569
optimized_preprocess_params  {'create_artificial_batch': False, 'hvg_flavor...
optimized_estimator_params                                {'n_components': 78}
optimized_graph_params       {'assignment_quantile': 0.32725183496615845, '...

[5/10] cellrank_bone_marrow
status=skipped_existing
best_model=pca
best_score=0.8161
pca_best_score=0.8161
gplvm_best_score=0.80885
preprocess params:
{
  "create_artificial_batch": true,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1238,
  "normalize": false
}
estimator params:
{
  "n_components": 100
}
graph params:
{
  "assignment_quantile": 0.357226467691233,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 15,
  "inter_edge_mode": "propagate_neighbors",
  "intra_fraction": 0.6246424191163701,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 4,
  "n_neighbors": 28,
  "neighbor_mode": "distance",
  "rank_correction": true,
  "symmetrize": true
}

                                                                             4
dataset                                                   cellrank_bone_marrow
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                        skipped_existing
best_model                                                                 pca
best_score                                                              0.8161
pca_best_score                                                          0.8161
gplvm_best_score                                                       0.80885
optimized_preprocess_params  {'create_artificial_batch': True, 'hvg_flavor'...
optimized_estimator_params                               {'n_components': 100}
optimized_graph_params       {'assignment_quantile': 0.357226467691233, 'ed...

[6/10] cellrank_lung
status=optimized
best_model=gplvm
best_score=0.63455
pca_best_score=0.62155
gplvm_best_score=0.63455
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1370,
  "normalize": false
}
estimator params:
{
  "n_components": 74
}
graph params:
{
  "assignment_quantile": 0.2525227870479052,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 8,
  "inter_edge_mode": "propagate_neighbors",
  "intra_fraction": 0.47508426379582436,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 3,
  "n_neighbors": 28,
  "neighbor_mode": "distance",
  "rank_correction": true,
  "symmetrize": true
}

                                                                             5
dataset                                                          cellrank_lung
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                               optimized
best_model                                                               gplvm
best_score                                                             0.63455
pca_best_score                                                         0.62155
gplvm_best_score                                                       0.63455
optimized_preprocess_params  {'n_top_genes': 1370, 'max_cells': 1000, 'min_...
optimized_estimator_params                                {'n_components': 74}
optimized_graph_params       {'n_neighbors': 28, 'intra_fraction': 0.475084...

[7/10] cellrank_pancreas
status=optimized
best_model=gplvm
best_score=0.93745
pca_best_score=0.8977
gplvm_best_score=0.93745
preprocess params:
{
  "create_artificial_batch": false,
  "hvg_flavor": "variance",
  "max_cells": 1000,
  "min_cell_genes": null,
  "min_gene_counts": 0,
  "n_top_genes": 1498,
  "normalize": false
}
estimator params:
{
  "n_components": 74
}
graph params:
{
  "assignment_quantile": 0.18118402833211514,
  "edge_weighting": "distance",
  "hubness_correction": "csls",
  "hubness_k": 12,
  "inter_edge_mode": "assignment",
  "intra_fraction": 0.4648268813971244,
  "metric": "euclidean",
  "mutual_neighbors": true,
  "n_inter_edges": 1,
  "n_neighbors": 26,
  "neighbor_mode": "distance",
  "rank_correction": true,
  "symmetrize": true
}

                                                                             6
dataset                                                      cellrank_pancreas
input_path                   /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
params_path                  /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b6...
status                                                               optimized
best_model                                                               gplvm
best_score                                                             0.93745
pca_best_score                                                          0.8977
gplvm_best_score                                                       0.93745
optimized_preprocess_params  {'n_top_genes': 1498, 'max_cells': 1000, 'min_...
optimized_estimator_params                                {'n_components': 74}
optimized_graph_params       {'n_neighbors': 26, 'intra_fraction': 0.464826...

[8/10] cellrank_reprogramming_schiebinger

The JSON parameter files written by this run are consumed directly by notebook 02:

```python
optimized_params = load_or_default_params(selected_dataset, dataset)
```

The CSV summary is only a run log; the JSON files in `data/optimized_params/` are the source of truth for downstream visualization and evaluation.