# Download Paper Datasets

Download the CLASP paper datasets that have stable programmatic sources into the project-level `data/` directory. The scIB immune datasets are multi-GB downloads.

In [1]:
from clasp.notebook_utils import (
    PAPER_DATASET_DOWNLOADS,
    download_datasets,
    paper_dataset_manifest,
    paper_datasets_requiring_manual_curation,
    resolve_project_root,
    summarize_downloads,
)


project_root = resolve_project_root()
data_dir = project_root / "data"
selected_datasets = PAPER_DATASET_DOWNLOADS
overwrite = False

paper_dataset_manifest(selected_datasets)

,dataset,filename,kind,batch_key,label_key,paper_group,source
0,scib_pancreas,human_pancreas_norm_complexBatch.h5ad,figshare,tech,celltype,scIB benchmark,https://figshare.com/articles/dataset/12420968
1,scib_lung_atlas,Lung_atlas_public.h5ad,figshare,batch,cell_type,scIB benchmark,https://figshare.com/articles/dataset/12420968
2,scib_immune_human,Immune_ALL_human.h5ad,figshare,batch,final_annotation,scIB benchmark,https://figshare.com/articles/dataset/12420968
3,scib_immune_human_mouse,Immune_ALL_hum_mou.h5ad,figshare,batch,final_annotation,scIB benchmark,https://figshare.com/articles/dataset/12420968
4,cellrank_bone_marrow,cellrank-bone-marrow.h5ad,url,sample,clusters,CellRank trajectory benchmark,https://cellrank.readthedocs.io/en/latest/api/...
5,cellrank_lung,cellrank-lung.h5ad,url,time,clusters,CellRank trajectory benchmark,https://cellrank.readthedocs.io/en/latest/api/...
6,cellrank_pancreas,cellrank-pancreas.h5ad,url,clusters,clusters,CellRank trajectory benchmark,https://cellrank.readthedocs.io/en/latest/api/...
7,cellrank_reprogramming_schiebinger,cellrank-reprogramming-schiebinger.h5ad,url,day,clusters,CellRank trajectory benchmark,https://cellrank.readthedocs.io/en/latest/api/...
8,cellrank_reprogramming_morris,cellrank-reprogramming-morris.h5ad,url,day,clusters,CellRank trajectory benchmark,https://cellrank.readthedocs.io/en/latest/api/...
9,zebrafish,cellrank-zebrafish.h5ad,url,Stage,lineages,development/time series,https://cellrank.readthedocs.io/en/latest/api/...

In [2]:
paper_datasets_requiring_manual_curation()

,dataset,paper_description,references,reason
0,Cancer benchmark collection,"11 cancer scRNA-seq studies: breast cancer, PD...","Azizi, Bassez, Slyper, Elyada, Peng, Bi, Karls...",The CLASP PDF names the studies via citations ...
1,Additional time-series collection,"Human hematopoietic differentiation, fetal lun...","Tusi, Travaglini, Plass, Tempora",The CLASP PDF names the biological datasets bu...

In [3]:
downloaded = download_datasets(selected_datasets, data_dir=data_dir, overwrite=overwrite)
downloaded

downloading: https://ndownloader.figshare.com/files/24539828
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/human_pancreas_norm_complexBatch.h5ad
downloading: https://ndownloader.figshare.com/files/24539942
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Lung_atlas_public.h5ad
downloading: https://ndownloader.figshare.com/files/25717328
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Immune_ALL_human.h5ad
downloading: https://ndownloader.figshare.com/files/25717166
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Immune_ALL_hum_mou.h5ad
downloading: https://ndownloader.figshare.com/files/35826944
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-bone-marrow.h5ad
downloading: https://ndownloader.figshare.com/files/25038224
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-lung.h5ad
downloading: https://ndownloader.figshare.com/files/25060877
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-pancreas.h5ad
downloading: https://ndownloader.figshare.com/files/28618734
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-reprogramming-schiebinger.h5ad
downloading: https://ndownloader.figshare.com/files/25503773
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-reprogramming-morris.h5ad
downloading: https://ndownloader.figshare.com/files/27265280
saved: /media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-zebrafish.h5ad

{'scib_pancreas': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/human_pancreas_norm_complexBatch.h5ad'),
 'scib_lung_atlas': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Lung_atlas_public.h5ad'),
 'scib_immune_human': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Immune_ALL_human.h5ad'),
 'scib_immune_human_mouse': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/Immune_ALL_hum_mou.h5ad'),
 'cellrank_bone_marrow': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-bone-marrow.h5ad'),
 'cellrank_lung': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-lung.h5ad'),
 'cellrank_pancreas': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-pancreas.h5ad'),
 'cellrank_reprogramming_schiebinger': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-reprogramming-schiebinger.h5ad'),
 'cellrank_reprogramming_morris': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-reprogramming-morris.h5ad'),
 'zebrafish': PosixPath('/media/fabrizio/06bb7271-2161-43a4-91f1-98f9b67e9ab2/home/fabrizio/code/clasp/data/cellrank-zebrafish.h5ad')}

In [4]:
summarize_downloads(downloaded, project_root=project_root, inspect_h5ad=False)

,dataset,path,file_size_gb,batch_key,label_key,source,paper_group
0,scib_pancreas,data/human_pancreas_norm_complexBatch.h5ad,0.294,tech,celltype,https://figshare.com/articles/dataset/12420968,scIB benchmark
1,scib_lung_atlas,data/Lung_atlas_public.h5ad,0.950,batch,cell_type,https://figshare.com/articles/dataset/12420968,scIB benchmark
2,scib_immune_human,data/Immune_ALL_human.h5ad,1.923,batch,final_annotation,https://figshare.com/articles/dataset/12420968,scIB benchmark
3,scib_immune_human_mouse,data/Immune_ALL_hum_mou.h5ad,3.975,batch,final_annotation,https://figshare.com/articles/dataset/12420968,scIB benchmark
4,cellrank_bone_marrow,data/cellrank-bone-marrow.h5ad,0.362,sample,clusters,https://cellrank.readthedocs.io/en/latest/api/...,CellRank trajectory benchmark
5,cellrank_lung,data/cellrank-lung.h5ad,0.160,time,clusters,https://cellrank.readthedocs.io/en/latest/api/...,CellRank trajectory benchmark
6,cellrank_pancreas,data/cellrank-pancreas.h5ad,0.033,clusters,clusters,https://cellrank.readthedocs.io/en/latest/api/...,CellRank trajectory benchmark
7,cellrank_reprogramming_schiebinger,data/cellrank-reprogramming-schiebinger.h5ad,1.375,day,clusters,https://cellrank.readthedocs.io/en/latest/api/...,CellRank trajectory benchmark
8,cellrank_reprogramming_morris,data/cellrank-reprogramming-morris.h5ad,1.485,day,clusters,https://cellrank.readthedocs.io/en/latest/api/...,CellRank trajectory benchmark
9,zebrafish,data/cellrank-zebrafish.h5ad,0.040,Stage,lineages,https://cellrank.readthedocs.io/en/latest/api/...,development/time series